### PR TITLE
chore(repo): migrate to nx v13.10 beta

### PR DESCRIPTION
**Pull request by AgentEnder**

### CODE REVIEW

**Comment by benpsnyder** [comment]
Can we please process and release this ASAP?

**Comment by AgentEnder** [comment]
Nothing in this PR should be blocking from an external POV, the main change is just that our doc generator plugin can be invoked without the workspace generator.

This PR will be updated and merged as soon as 13.10 releases, but the plugin doesn't bump to betas generally. 

Is there something in particular that is blocking your team?

**Comment by AgentEnder** [comment]
Hmmmm, I actually think I know what's going on. You'll need to just bump the nx-dotnet version manually in package.json for now. If migrating from any recent version there shouldn't be any associated migrations IIRC.

**Comment by benpsnyder** [comment]
Thanks guys! Excited for this next release. I'm using nx-dotnet at a large enterprise and porting over all their monolithic .net framework 4.8 code into domain drive libs ... it's an absolute pleasure using this plugin.  We hope to actively contribute soon on the issues queue and with pull requests

Cheers

**Comment by AgentEnder** [comment]
@benpsnyder That's great to hear. I'm releasing a patch real quick that I think should take care of the issue you are having. When we consolidated nx/tao/cli on the Nx repo the tao package isn't installed during migrate now. That causes the module not found error. 

Definitely leave some feedback in #83 if you can, any details about workspace size, enterprise type + size, workspace consistency (i.e. what else is in it), can definitely help in many ways.

**Comment by benpsnyder** [comment]
> @benpsnyder That's great to hear. I'm releasing a patch real quick that I think should take care of the issue you are having. When we consolidated nx/tao/cli on the Nx repo the tao package isn't installed during migrate now. That causes the module not found error.
> 
> Definitely leave some feedback in #83 if you can, any details about workspace size, enterprise type + size, workspace consistency (i.e. what else is in it), can definitely help in many ways.

Let me get permission to do that from the client; I have bookmarked it and would be glad to make informal or formal documentation on the enterprise use case.

The biggest game-changer is when nx-dotnet is implement alongside Dapr and @nx-tools/nx-docker .... let me give you a taste of that

image
image
image
image
image
image

We can use Typescript for our frontend (Angular) apps, supporting backend i/o APIs in Typescript (NestJS), share models between them, then use nx-dotnet, nx-go, [...insert language of choice], and marry them all together elegantly with service-to-service invocation with Dapr.  Local development is actually faster with Dapr executing nx in slim-mode (I don't know how, but that's our experience) and bundling for test/staging/production releases in containers with Dapr sidecar scaling benefits is a dream.  We're almost out of BETA with this above configuration and trying to upgrade production.

Let me ask if I can share more details.

With nx-dotnet, we're developing a convention and tagging system for the libraries, given that this enterprise operates in multiple countries with different requirements, and we like seeing the affected graph and ability to structure our unit tests.

**Comment by AgentEnder** [comment]
@benpsnyder Are you currently using any codegen to support sharing models between the .NET / whatever apis and the TS APIs? The idea for the unimplemented @nx-dotnet/typescript package is to generate TS interfaces from your API apps, ideally based on swagger doc generation.

**Comment by benpsnyder** [comment]
> @benpsnyder Are you currently using any codegen to support sharing models between the .NET / whatever apis and the TS APIs? The idea for the unimplemented @nx-dotnet/typescript package is to generate TS interfaces from your API apps, ideally based on swagger doc generation.

That is highly desirable and we would immediately adopt that if you have some tips to share ... we developed an opinionated DDD approach and library structure (going to make an Nx plugin and publish) that looks something like this (from an internal project)

```bash
######
###### domain: project
######

# project/domain
yarn nx generate @nrwl/js:library --buildable --no-interactive --tags='domain-scope:project,platform:any,framework:any,type:domain' --directory='project' --name='domain'
yarn nx generate @nrwl/nest:library --buildable --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:nest,platform:backend,type:domain' --directory='project/domain' --name='infrastructure'

# project/frontend/shell/client
yarn nx generate @nrwl/angular:library --buildable --routing --compilationMode='full' --simpleModuleName --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:angular,platform:frontend,type:shell' --directory='project/frontend/shell' --prefix='project' --name='router'
yarn nx generate @nrwl/angular:library --buildable --routing --compilationMode='full' --simpleModuleName --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:angular,platform:frontend,type:shell' --directory='project/frontend/shell' --prefix='project' --name='client'
yarn nx generate @nrwl/angular:library --buildable --routing --compilationMode='full' --simpleModuleName --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:angular,platform:frontend,type:shell' --directory='project/frontend/shell' --prefix='project' --name='user'

# project/frontend/feature
yarn nx generate @nrwl/angular:library --buildable --routing --compilationMode='full' --simpleModuleName --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:angular,platform:frontend,type:feature' --directory='project/frontend/feature' --prefix='project' --name='projects'

# project/frontend/ui/
yarn nx generate @nrwl/angular:library --buildable --compilationMode='full' --simpleModuleName --standaloneConfig --strict --no-interactive --tags='domain-scope:project,platform:frontend,framework:angular,type:ui' --directory='project/frontend/ui' --prefix='project' --name='controls'


# project/backend/kernel/
yarn nx generate @nrwl/nest:library --buildable --controller --service --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:nest,platform:backend,type:kernel' --directory='project/backend/kernel' --name='legacy-code'
yarn nx generate @nrwl/nest:library --buildable --controller --service --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:nest,platform:backend,type:kernel' --directory='project/backend/kernel' --name='portfolio-safe'
yarn nx generate @nrwl/nest:library --buildable --controller --service --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:nest,platform:backend,type:kernel' --directory='project/backend/kernel' --name='backlog-themes'
yarn nx generate @nrwl/nest:library --buildable --controller --service --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:nest,platform:backend,type:kernel' --directory='project/backend/kernel' --name='backlog-milestones'
yarn nx generate @nrwl/nest:library --buildable --controller --service --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:nest,platform:backend,type:kernel' --directory='project/backend/kernel' --name='backlog-solutions'
yarn nx generate @nrwl/nest:library --buildable --controller --service --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:nest,platform:backend,type:kernel' --directory='project/backend/kernel' --name='backlog-requirements'
yarn nx generate @nrwl/nest:library --buildable --controller --service --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:nest,platform:backend,type:kernel' --directory='project/backend/kernel' --name='backlog-tasks'

yarn nx generate @nrwl/nest:library --buildable --controller --service --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:nest,platform:backend,type:kernel' --directory='project/backend/kernel' --name='azure-devops'
yarn nx generate @nrwl/nest:library --buildable --controller --service --standaloneConfig --strict --no-interactive --tags='domain-scope:project,framework:nest,platform:backend,type:kernel' --directory='project/backend/kernel' --name='d365-project-operations'
```
eslint dep tags
```bash
{
  "root": true,
  "ignorePatterns": ["**/*", "!app-blog/**/*", "!app-blog/*"],
  "plugins": ["jsdoc", "eslint-plugin-tsdoc", "ngrx", "@nrwl/nx"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "extends": ["plugin:jsdoc/recommended", "plugin:import/recommended"],
      "settings": {
        "import/resolver": {
          "typescript": {
            "alwaysTryTypes": true
          },
          "node": {
            "extensions": [".js", ".jsx", ".ts", ".tsx"]
          }
        }
      },
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "enforceBuildableLibDependency": false,
            "allow": [],
            "depConstraints": [
              {
                "sourceTag": "platform:frontend",
                "onlyDependOnLibsWithTags": [
                  "platform:any",
                  "platform:frontend"
                ],
                "bannedExternalImports": ["typeorm*", "sequelize*"]
              },
              {
                "sourceTag": "platform:backend",
                "onlyDependOnLibsWithTags": [
                  "platform:any",
                  "platform:backend"
                ],
                "bannedExternalImports": ["@ngrx/*", "react*", "@angular/*"]
              },
              {
                "sourceTag": "platform:any",
                "onlyDependOnLibsWithTags": ["platform:any"]
              },
              {
                "sourceTag": "framework:any",
                "onlyDependOnLibsWithTags": ["framework:any"],
                "bannedExternalImports": ["@angular/*", "react*", "@nestjs/*"]
              },
              {
                "sourceTag": "framework:nest",
                "onlyDependOnLibsWithTags": [
                  "framework:any",
                  "framework:nest",
                  "platform:any",
                  "platform:backend"
                ],
                "bannedExternalImports": ["@angular/*", "react*"]
              },
              {
                "sourceTag": "framework:angular",
                "onlyDependOnLibsWithTags": [
                  "framework:any",
                  "framework:angular",
                  "platform:any",
                  "platform:frontend"
                ],
                "bannedExternalImports": ["@nestjs/*"]
              },
              {
                "sourceTag": "type:domain",
                "onlyDependOnLibsWithTags": ["type:domain"]
              },
              {
                "sourceTag": "domain-scope:shared",
                "onlyDependOnLibsWithTags": [
                  "domain-scope:shared",
                  "domain-scope:project",
                  "domain-scope:service",
                  "domain-scope:time",
                  "domain-scope:resource"
                ]
              },
              {
                "sourceTag": "domain-scope:user",
                "onlyDependOnLibsWithTags": [
                  "domain-scope:shared",
                  "domain-scope:user"
                ]
              },
              {
                "sourceTag": "domain-scope:service",
                "onlyDependOnLibsWithTags": [
                  "domain-scope:shared",
                  "domain-scope:service",
                  "domain-scope:time",
                  "domain-scope:resource"
                ]
              },
              {
                "sourceTag": "domain-scope:project",
                "onlyDependOnLibsWithTags": [
                  "domain-scope:shared",
                  "domain-scope:project",
                  "domain-scope:time",
                  "domain-scope:resource"
                ]
              },
              {
                "sourceTag": "domain-scope:time",
                "onlyDependOnLibsWithTags": [
                  "domain-scope:shared",
                  "domain-scope:time",
                  "domain-scope:resource"
                ]
              },
              {
                "sourceTag": "domain-scope:resource",
                "onlyDependOnLibsWithTags": [
                  "domain-scope:shared",
                  "domain-scope:resource",
                  "domain-scope:time"
                ]
              },
              {
                "sourceTag": "type:app",
                "onlyDependOnLibsWithTags": [
                  "type:cli",
                  "type:kernel",
                  "type:shell",
                  "type:feature",
                  "type:ui",
                  "type:utility",
                  "type:database",
                  "type:domain"
                ]
              },
              {
                "sourceTag": "type:feature",
                "onlyDependOnLibsWithTags": [
                  "type:domain",
                  "type:feature",
                  "type:data-access",
                  "type:modal",
                  "type:utility",
                  "type:ui"
                ]
              },
              {
                "sourceTag": "type:ui",
                "onlyDependOnLibsWithTags": [
                  "type:domain",
                  "type:utility",
                  "type:ui"
                ]
              },
              {
                "sourceTag": "type:kernel",
                "onlyDependOnLibsWithTags": [
                  "type:domain",
                  "type:kernel",
                  "type:database",
                  "type:utility"
                ]
              },
              {
                "sourceTag": "type:cli",
                "onlyDependOnLibsWithTags": [
                  "type:domain",
                  "type:kernel",
                  "type:cli"
                ]
              },
              {
                "sourceTag": "type:modal",
                "onlyDependOnLibsWithTags": [
                  "type:domain",
                  "type:data-access",
                  "type:utility",
                  "type:ui"
                ]
              },
              {
                "sourceTag": "type:utility",
                "onlyDependOnLibsWithTags": [
                  "type:domain",
                  "type:utility",
                  "type:database"
                ]
              },
              {
                "sourceTag": "type:database",
                "onlyDependOnLibsWithTags": [
                  "type:domain",
                  "type:database",
                  "type:utility"
                ]
              }
            ]
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "rules": {
        "@typescript-eslint/no-explicit-any": 0,
        "max-len": 0
      }
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nrwl/nx/javascript"],
      "rules": {}
    }
  ],
  "settings": {
    "jsdoc": {
      "tagNamePreference": {
        "todo": {
          "message": "We expect immediate perfection, so don't leave to-dos in your code. :)"
        }
      }
    },
    "node": {
      "allowModules": ["electron"],
      "resolvePaths": ["__dirname"],
      "tryExtensions": [".js", ".json", ".node", ".ts"]
    }
  }
}

```

We use the "kernel" library type like a frontend "feature" ... whereas "feature" uses NgRx from a "shared/data-access", the "kernel" also follows a CQRS pattern. "domain-infrastructure" is a NestJS lib, importing from "domain" which is just a typescript lib.

image

Beautiful domain model
image

**Comment by benpsnyder** [comment]
FYI code shared above is all WIP based on refactoring being done, but you can glean from it the approach we're taking.

I've taken some concepts from https://github.com/Sairyss/domain-driven-hexagon ... and we try to make our base models, enums, interfaces, classes, etc in the typescript (backend/frontend agnostic) "domain" lib.

This gives us a "full stack typesafe" approach to our building the frontend/backend stuff with the javascript team.  It's so lovely.

I would absolutely love it if we could generate shared models between dotnet and typescript in an elegant way.

**Comment by AgentEnder** [comment]
Ok, yeah that stuff is interesting and it looks like you have a nice workflow going on the JS thing. Getting the full integration for the cross-stack dependencies is beautiful once you get it working.

Regarding the type generation, I am tracking that effort here: https://github.com/nx-dotnet/nx-dotnet/issues/4. Its been a project goal from the beginning, but beyond thinking about it and research there hasn't been any work started in the area. It'll be a sizable effort, and I want to get the DX right.

If you want to read through the thoughts there, maybe some feedback could accelerate those plans.

**Pull request merged**
