### PR TITLE
fix: use exact project paths

### LINKED ISSUE #125: [BUG] Project is being captured as a dependency even though it is not
**Describe the bug**
A project is wrongly captured as a dependency **when it starts with the same name as a project that is actually a dependency.**

**To Reproduce**
1. Create 3 projects (`dep-project`, `dep-project-foo`, `target-project`) 
libs/
├─ target-project/TargetProject.csproj
├─ dep-project-foo/DepProject.Foo.csproj
├─ dep-project/DepProject.csproj

2. Add `dep-project-foo` as a project reference in `target-project`
3. Run `nx dep-graph`
4. Not only is `dep-project-foo` a dependency of `target-project` but also `dep-project`

**Expected behavior**
`target-project` should only have one dependency: `dep-project-foo`

**Additional context**
I think the problem is here:
https://github.com/nx-dotnet/nx-dotnet/blob/3ca8a58536d24c0b496d76d370a5b70e7b3b139c/packages/utils/src/lib/utility-functions/workspace.ts#L74

Comparing against `` `${path}\\` `` appears to fix the issue.

### PR DESCRIPTION
**Pull request by pemsbr**
fixes #125

### CODE REVIEW

**Comment by AgentEnder** [comment]
Looks like e2e failed, do you care to check whats going on? The failing test shows that the dep-graph portion is not working quite right now.

**Comment by pemsbr** [comment]
@AgentEnder the test passes in my machine, not sure what the problem might be

**Comment by AgentEnder** [comment]
@pemsbr I can confirm, this appears to only be happening on CI... Let me look into it, not sure why dep-graph parsing would only work on local...

**Comment by AgentEnder** [comment]
...gh done something weird here. I still have your original commit. I'm going to open a new PR with it to get this fixed.

**Comment by AgentEnder** [comment]
@allcontributors add @pemsbr for code

**Pull request closed without merging**
