### PR TITLE
feat(core): add argument forwarding to dotnet new

### PR DESCRIPTION
**Pull request by Soulusions**
I've moved my version of this feature to its own PR.
This version is able to accept args passed after `--` using the additionalProperties feature from JSON-Schema.
Closes: #398 
Closes: #262

### CODE REVIEW

**Comment by Soulusions** [comment]
Just wanted to update this PR with a couple notes:
This fixes #398 and #262 
And, if the code for this executor is fine to be merged, I could also modify it to work with the serve executor, fixing #295 and #336

**Comment by Soulusions** [comment]
But yeah, anyways, I'd love to have your opinion on this @AgentEnder

**Comment by nslusher-sf** [comment]
@AgentEnder Have you had a chance to review this?

**Review by AgentEnder — APPROVED** [review]
Hey @Soulusions 🎉 

Sorry this has taken **_forever_** to get to, but it looks really good. I appreciate the e2e and unit tests that you've added, as they give the confidence that the syntax is working exactly how I'd like. I'll merge it now, and you can expect a new version out as soon as I get a few other things lined up (hopefully before next week).

For anyone else watching - the project is alive, but no changes have been required recently and while this is a valuable contribution its not been super necessary and I've put off merging new features in the meantime. The **_main_** reason for a new release at any point would be that compatibility with newer versions of Nx necessitated changes, or something pressing came up. I appreciate the users of the plugin though and am happy to have been able to spend some more time on this recently.

**Comment by AgentEnder** [comment]
@all-contributors add @Soulusions for code

**Pull request merged**
