### PR TITLE
chore(repo): fix buildTarget value for demo-frontend

### PR DESCRIPTION
**Pull request by mnlttt**

### CODE REVIEW

**Review by AgentEnder — APPROVED** [review]

**Comment by AgentEnder** [comment]
Hey @mnlttt! This looks good, thanks for the PR 🎉. Can you update your commit message to match our standards?

**Comment by AgentEnder** [comment]
You can fix it with either `git rebase -i` or `git commit --amend`

**Comment by mnlttt** [comment]
@AgentEnder does it look good now?

**Comment by AgentEnder** [comment]
Itll pass commitlint that way, but its not really accurate. I'd probably do `chore(repo)` on this since its just cleaning up something in the repo thats unrelated to the code.

Don't worry about it though, I'll change that when I merge it.

**Pull request merged**
