### PR TITLE
fix(core): restore project.json generation

### PR DESCRIPTION
**Pull request by mhdubose**
Update generator to create `project.json` but omit targets if they can be inferred by Nx Crystal

### CODE REVIEW

**Review by AgentEnder — APPROVED** [review]
Ideallistically we'd update the other generators that look for project configurations etc and fix them up s.t. they work better with crystal (aka inference). Plugins **_can_** infer full projects, which is what we are doing here, its just some devkit methods won't be able to find them. 

For a short term fix though, this will work well.

**Comment by md-owes** [comment]
since this PR is still waiting to be merged. Meanwhile folks like me who cannot wait can downgrade to the previous version i.e. 2.1.2. For beginners, you need to have the following in your package.json

```
"devDependencies": {
    "@nx-dotnet/core": "2.1.2"
    }
```

and then do `npm i`. Now it should work.

**Comment by mhdubose** [comment]
any updates @AgentEnder on when we can get this in as a temporary fix, or a better long term fix is coming?

**Comment by AgentEnder** [comment]
Closing this out, 2.3.0 should have much better crystal support.

**Pull request closed without merging**
