### PR TITLE
fix(core): avoid terminal popups on windows

### PR DESCRIPTION
**Pull request by Den-dp**
Helps to avoid Terminal popups on Windows by enforcing `{ windowsHide: true }`.

### CODE REVIEW

**Review by AgentEnder — APPROVED** [review]

**Comment by Den-dp** [comment]
Hey @AgentEnder, any suggestions on how to fix failing CI?

I also tried running this failing `nx run core-e2e:e2e` task on the master branch and got the same errors as here, so it looks like not my changes introduced this regression

master:
image
pr:
image

**Comment by getlarge** [comment]
@Den-dp Your PR should be able to pass the tests now!

**Comment by Den-dp** [comment]
@getlarge wow, sounds great! Thanks a lot

I'll rebase it and check it out

**Comment by Den-dp** [comment]
hey @AgentEnder, would you mind approving CI re-run

**Pull request merged**
