### PR TITLE
Add generator option for standalone projects

### LINKED ISSUE #70: [Feature] Add option for standalone projects
**Is your feature request related to a problem? Please describe.**
I recently migrated my workspace to Nx 12.5 and switched to standalone project configurations. When I added a new .NET project to my workspace, the new project used the old `nx.json` and `workspace.json` configuration.

**Describe the solution you'd like**
I would like a new option added to the app and lib generators that generates the project configuration in standalone format.

**Describe alternatives you've considered**
Alternatively, I could write my own wrapper generator/script that moves the project configuration after it has been written, or I use the Nx-official generator to migrate the newly created project into the new format.

**Additional context**
Generating project configuration in the new standalone format is a one-parameter change to `addProjectConfiguration`. The app and lib generators just need a new parameter which will be passed through to `addProjectConfiguration`.

### PR DESCRIPTION
**Pull request by bcallaghan-et**
Add a new option to the app, lib, and test generators to build standalone `project.json` files instead of placing all configuration in `workspace.json`. Update the local workspace to use the new standalone project configurations.

Resolves #70

### CODE REVIEW

**Comment by AgentEnder** [comment]
@bcallaghan-et  Looking into failing tests, to fix `nx-ghpages:test` you need to add the following:

```typescript
import * as fs from 'fs';

jest.mock('fs', () => ({
  ...(jest.requireActual('fs') as typeof fs),
  stat: (path: string, cb: (err: unknown, stats: unknown) => void) =>
    cb(null, {}),
}));
```

**Comment by bcallaghan-et** [comment]
@AgentEnder The e2e tests fail locally as well. Do you have any guidance why yarn would fail, or why `@nx-dotnet/core/package.json` can't be found?

**Comment by AgentEnder** [comment]
Hey, yeah. Make sure to run the e2e with `npm run e2e` or `yarn e2e` instead of through Nx.

**Comment by bcallaghan-et** [comment]
I tried `yarn e2e` and that produced the same errors.

**Pull request merged**
