### PR TITLE
fix(core): adjust gitignore to support generation with directory

### PR DESCRIPTION
**Pull request by Tungsten78**
- include typo fix

### CODE REVIEW

**Comment by AgentEnder** [comment]
@Tungsten78 This may not be needed anymore, since #596 includes a fix that moves the generated obj directory into dist. Can you check if its needed in a new workspace using latest?

**Comment by Tungsten78** [comment]
@AgentEnder  Assuming I'm checking the right thing it appears to continue as a problem.

image

**Comment by AgentEnder** [comment]
Ah, I forgot about the nuget files. That's my bad.

My concern with using a globstar for this stems from projects containing source directories that have subfolders named bin, as is common for nodejs cli tools. A lot of times a node project may have a bin folder at root even...

We could instead list out the files that are still generated in these folders automatically perhaps? We could theoretically even just generate a .gitignore within the new dotnet apps roots and list bin / obj, Nx doesn't obey nested gitignores as far as globbing / dependency tracing but it should be fine for this use case since git does obey them.

**Comment by Tungsten78** [comment]
Any concerns I’d it were only obj?  
I hear you about making too many assumptions when applying ignores at the workspace level. 

Writing a .gitignore I’m the generated projects might be safest.

**Comment by AgentEnder** [comment]
Generally I was trying to avoid the root gitignores since Nx doesn't currently obey them (we'd like to, but it's actually a non trivial performance cost). That said, the remainder of those directories is pretty slim, and Nx trying to read them shouldn't cause any runtime errors so we should be OK to do that now.

If you want to close this PR and open another with that approach you can, or you can reuse this one, or if you'd rather I can take a look sometime in the next week or so

**Comment by Tungsten78** [comment]
To ensure we're on the same page...

We are going to address the aforementioned issue by moving the ignore clauses
- from the workspace .gitignore into project based .gitignore.

Example: `[app,lib]/{directory}/{project}/.gitignore`
```
obj
bin
```

**Comment by AgentEnder** [comment]
Yeah, I think that makes the most sense. It'll move that logic outside of the init generator and into the generate-project util

**Comment by Tungsten78** [comment]
Full disclaimer: having issues running the test suite on my windows-based machine.  Might need to use a mac?

`Error: spawnSync echo ENOENT`

```Error: dotnet execution returned status code null
    at DotNetClient.logAndExecute (C:\Users\CML0906\Source\nx-dotnet\packages\dotnet\src\lib\core\dotnet.client.ts:239:13)
    at DotNetClient.new (C:\Users\CML0906\Source\nx-dotnet\packages\dotnet\src\lib\core\dotnet.client.ts:36:17)
    at initToolManifest (C:\Users\CML0906\Source\nx-dotnet\packages\core\src\generators\init\generator.ts:88:21)
    at C:\Users\CML0906\Source\nx-dotnet\packages\core\src\generators\init\generator.ts:48:3
    at Generator.next (<anonymous>)
    at C:\Users\CML0906\Source\nx-dotnet\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\CML0906\Source\nx-dotnet\node_modules\tslib\tslib.js:114:16)
    at initGenerator (C:\Users\CML0906\Source\nx-dotnet\packages\core\src\generators\init\generator.ts:11:20)
    at C:\Users\CML0906\Source\nx-dotnet\packages\core\src\generators\utils\generate-project.ts:169:24
```

**Comment by AgentEnder** [comment]
Ideally it would "just work" regardless, but for my local dev I use WSL2 on windows. If you get spare time to help track down inconsistent results on base windows, any fixes to that DX would be appreciated

**Comment by Tungsten78** [comment]
Most of the test suite works on my Mac.   Still have some failures.

Also, not having luck with `yarn publish-local`.
- It doesn't like `run-p`.  Hacking a bit around it, it doesn't like `e2e-registry` either.  I'm not sure where this comes from?

**Comment by AgentEnder** [comment]
This seems like the likely culprit: https://github.com/nodejs/node-v0.x-archive/issues/6425

**Comment by Tungsten78** [comment]
> This seems like the likely culprit: [nodejs/node-v0.x-archive#6425](https://github.com/nodejs/node-v0.x-archive/issues/6425)

"use a better operating system". 😂 
* I'll take a look to see if there's a solution.    
* Wouldn't mind getting publish-local working too(#309), but then super odd doesn't work on the Mac.  I'll give WSL a shot tomorrow.

**Comment by AgentEnder** [comment]
Yeah, it's been a while since I looked at the windows dev experience for the repo. Probably several small things.

**Comment by AgentEnder** [comment]
I would expect publish local to work on WSL, Mac, or Linux so if that's failing on those platforms it may be more interesting.

It works on Ubuntu and WSL for sure given CI and my local env

**Review by AgentEnder — APPROVED** [review]

**Pull request merged**
